backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
# public_folder: /img

collections:
  - name: "writing"
    label: "Writing"
    label_singular: "Writing"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{title}}/index"
    view_groups:
      - label: Category
        field: category
      - label: Topic
        field: topic
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["writing", "poetry", "tutorial"],
        }
      - {
          label: "Topic",
          name: "topic",
          widget: "select",
          options:
            [
              "general",
              "design",
              "finance",
              "relationship",
              "cooking",
              "craft",
              "faith",
              "communication",
            ],
          default: ["general"],
        }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - {
          label: "Author",
          name: "author",
          widget: "select",
          options: ["Benjamin", "Huey Lin"],
          default: ["Benjamin"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
